const nav=document.querySelector('.nav'),toggle=document.querySelector('.menu-toggle');toggle?.addEventListener('click',()=>nav.classList.toggle('open'));document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const tabs=document.querySelectorAll('.tab'),cards=document.querySelectorAll('.dish-card'),search=document.querySelector('#menuSearch');function filterMenu(){const active=document.querySelector('.tab.active')?.dataset.filter||'all',q=(search.value||'').toLowerCase().trim();cards.forEach(c=>{const ok=(active==='all'||c.dataset.cat===active)&&(!q||c.dataset.name.toLowerCase().includes(q));c.style.display=ok?'flex':'none'})}tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');filterMenu()}));search?.addEventListener('input',filterMenu);
const lightbox=document.querySelector('#lightbox'),img=document.querySelector('#lightboxImg');function openBox(src){img.src=src;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeBox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.querySelectorAll('[data-img]').forEach(x=>x.addEventListener('click',()=>openBox(x.dataset.img)));document.querySelector('.lightbox-close')?.addEventListener('click',closeBox);lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeBox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBox()});document.querySelector('#year').textContent=new Date().getFullYear();
// Shopping cart + WhatsApp ordering
const cart=[];const cartDrawer=document.querySelector('#cartDrawer'),cartOverlay=document.querySelector('#cartOverlay');
function rupee(n){return '₹'+Number(n).toLocaleString('en-IN')}
function openCart(){cartDrawer?.classList.add('open');cartOverlay?.classList.add('open');cartDrawer?.setAttribute('aria-hidden','false')}
function closeCart(){cartDrawer?.classList.remove('open');cartOverlay?.classList.remove('open');cartDrawer?.setAttribute('aria-hidden','true')}
document.querySelector('#cartBtn')?.addEventListener('click',openCart);document.querySelector('#mobileCart')?.addEventListener('click',openCart);document.querySelector('#cartClose')?.addEventListener('click',closeCart);cartOverlay?.addEventListener('click',closeCart);
document.querySelectorAll('.add-btn').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.dish-card');const name=card.dataset.name;const price=Number((card.querySelector('strong').textContent||'').replace(/[^0-9.]/g,''));const found=cart.find(x=>x.name===name);if(found)found.qty++;else cart.push({name,price,qty:1});renderCart();openCart()}));
function renderCart(){const box=document.querySelector('#cartItems');let total=0,count=0;if(!cart.length){box.innerHTML='<p class="cart-empty">Your cart is empty. Add dishes from the menu.</p>'}else{box.innerHTML=cart.map((x,i)=>{total+=x.price*x.qty;count+=x.qty;return `<div class="cart-row"><div><strong>${x.name}</strong><div>${rupee(x.price)} × ${x.qty}</div><div class="qty"><button type="button" data-minus="${i}">−</button><span>${x.qty}</span><button type="button" data-plus="${i}">+</button></div></div><strong>${rupee(x.price*x.qty)}</strong></div>`}).join('');box.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);renderCart()});box.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty++;renderCart()})}document.querySelector('#cartTotal').textContent=rupee(total);document.querySelector('#cartCount').textContent=count;document.querySelector('#mobileCartCount').textContent=count}
document.querySelector('#orderForm')?.addEventListener('submit',e=>{e.preventDefault();if(!cart.length){alert('Please add at least one dish to your cart.');return}const name=document.querySelector('#customerName').value.trim(),phone=document.querySelector('#customerPhone').value.trim(),address=document.querySelector('#customerAddress').value.trim(),type=document.querySelector('#orderType').value;let total=0;const lines=cart.map(x=>{total+=x.price*x.qty;return `• ${x.name} × ${x.qty} = ${rupee(x.price*x.qty)}`}).join('\n');const msg=`Hello J-S Spice Garden Restaurant,\n\nNew ${type} order from website:\n\n${lines}\n\nTotal: ${rupee(total)}\n\nCustomer: ${name}\nPhone: ${phone}\nAddress: ${type==='Delivery'?address:'Pickup from restaurant'}\n\nPlease confirm the order and final delivery/payment details.`;window.open('https://wa.me/918522889977?text='+encodeURIComponent(msg),'_blank');});
renderCart();
